export const portfolio = [
    {
        id: 1,
        img: "assets/img/portfolio-1.jpg",
        alt: "tripnight",
        title: "Tripnight.com",
        data_target: "#portfolioItem1",
        href: "https://tripnight.netlify.app",
    },
    {
        id: 2,
        img: "assets/img/portfolio-2.jpg",
        alt: "astore-moda",
        title: "Astore-moda",
        data_target: "#portfolioItem2",
        href: "https://astore-moda.netlify.app",
    },
    {
        id: 3,
        img: "assets/img/portfolio-3.jpg",
        alt: "agrocery cart",
        title: "Grocery Cart",
        data_target: "#portfolioItem3",
        href: "https://agrocery-cart.netlify.app",
    },
    {
        id: 4,
        img: "assets/img/portfolio-4.jpg",
        alt: "web shop",
        title: "Asport Shop",
        data_target: "#portfolioItem4",
        href: "https://asport-shop.netlify.app",
    },
    {
        id: 5,
        img: "assets/img/portfolio-5.jpg",
        alt: "lottery",
        title: "Lottery Malta",
        data_target: "#portfolioItem5",
        href: "https://instore.lottery.mt",
    },
    {
        id: 6,
        img: "assets/img/portfolio-6.jpg",
        alt: "food 4u",
        title: "Food4U",
        data_target: "#portfolioItem6",
        href: "https://food-4u.netlify.app",
    },
]

export const modal = [
    {
        id: "portfolioItem1",
        img: "assets/img/portfolio-1.jpg",
        alt: "tripnight",
        title: "Tripnight.com",
        description_1: `Tripnight.com is a complete full-stack hotel booking platform built from scratch with React. It features a user booking interface, admin CMS dashboard, Node.js backend, MySQL database, Redux Toolkit state management, Stripe payments, and Cloudinary for image storage.`,
        subtitle: "How does this app work?",
        description_2: [
            "Search for accommodations by destination, dates, number of guests (adults, children) and rooms",
            "Browse search results with hotel cards and key information",
            "View detailed hotel description, room types, pricing, and availability",
            "User registration and login required to make a reservation",
            "Select desired room and proceed to booking summary page",
            "Review full reservation details including total price and dates",
            "Secure payment processing via Stripe",
            "Admin dashboard (CMS) with full CRUD operations for hotels, rooms, and users",
            "Cloudinary integration for uploading and managing hotel/room images",
            "Fully responsive design for desktop and mobile devices"
        ],
        href: "https://tripnight.netlify.app",
    },
    {
        id: "portfolioItem2",
        img: "assets/img/portfolio-2.jpg",
        alt: "astore-moda",
        title: "Astore-moda",
        description_1: `Astore Moda is a full-stack fashion e-commerce platform built from scratch. It features a modern React frontend with Redux Toolkit, Node.js backend, MySQL database, Stripe payments, and Cloudinary for image management.`,
        subtitle: "How does this app work?",
        description_2: [
            "Browse women's, men's, and children's clothing collections",
            "Advanced filtering by category, price, size, color, and more",
            "Product detail page with multiple images, description, sizes, and pricing",
            "Add items to cart with quantity selection",
            "Wishlist / Favorites functionality to save items for later",
            "Shopping cart with real-time subtotal calculation",
            "Continue shopping or proceed to checkout",
            "Review order summary and total price",
            "Secure payment processing via Stripe",
            "Admin panel with CRUD operations for products (implied from full-stack setup)",
            "Cloudinary integration for product image upload and optimization",
            "Fully responsive design optimized for mobile and desktop"
        ],
        href: "https://astore-moda.netlify.app",
    },
    {
        id: "portfolioItem3",
        img: "assets/img/portfolio-3.jpg",
        alt: "Grocery Cart",
        title: "Grocery Cart",
        description_1: `Grocery Cart is a full-stack online grocery shopping platform built with React (frontend) and Node.js + MySQL (backend). It features user authentication, shopping cart, secure Stripe payments, order history, and a complete admin panel for managing products and orders.`,
        subtitle: "How does this app work?",
        description_2: [
            "Frontend: React with Context API for global state management",
            "Styling: Tailwind CSS",
            "Backend: Node.js + Express + MySQL database",
            "User authentication & registration (Login / Signup)",
            "Protected routes for authenticated users",
            "Order history – users can view all their past orders and order details",
            "User profile management",
            "Admin panel with full CRUD operations (products, categories, orders)",
            "Secure payment processing with Stripe",
            "Advanced shopping cart (add, update quantity, remove items)",
            "Product search and category-based browsing",
            "Checkout flow with order summary and confirmation",
            "Fully responsive design (mobile-first)"
        ],
        href: "https://agrocery-cart.netlify.app",
    },
    {
        id: "portfolioItem4",
        img: "assets/img/portfolio-4.jpg",
        alt: "web shop",
        title: "Asport Shop",
        description_1: `ASport Shop is a modern frontend e-commerce web application built with React. It offers a seamless shopping experience for sporting goods and apparel, allowing users to browse products, select variations, preview selections, and complete purchases through a registration and payment flow.`,
        subtitle: "How does this app work?",
        description_2: [
            "Browse a wide selection of sporting goods and apparel",
            "View detailed product pages with images and descriptions",
            "Select product variations such as size and color",
            "Add items directly via 'Buy Now' button",
            "Preview selected items before checkout",
            "User registration and account creation",
            "Enter delivery information (address, country, region, city)",
            "Secure checkout with credit card payment options",
            "Clean and responsive user interface",
            "Mobile-friendly design"
        ],
        href: "https://asport-shop.netlify.app",
    },
    {
        id: "portfolioItem5",
        img: "assets/img/portfolio-5.jpg",
        alt: "lottery",
        title: "Lottery Malta",
        description_1: `Lottery.mt is a modern React-based web application designed for lottery enthusiasts. Users can explore various lottery games, view the latest drawing results, and access detailed historical statistics to make informed betting decisions.`,
        subtitle: "How does this app work?",
        description_2: [
            "Browse and explore a variety of lottery games",
            "View the most recent drawing results in real-time",
            "Access comprehensive statistics and history of all past draws",
            "Designed exclusively for adults aged 18 and over",
            "Promotes safe and responsible gaming environment",
            "Clean, intuitive and interactive user interface",
            "Fully responsive design optimized for mobile and desktop",
            "Easy navigation and quick access to important information"
        ],
        href: "https://instore.lottery.mt",
    },
    {
        id: "portfolioItem6",
        img: "assets/img/portfolio-6.jpg",
        alt: "food 4u",
        title: "Food4U",
        description_1: `Food4U is a full-stack food delivery web application built with React, Node.js, MySQL, Redux for state management, Stripe for payments, and Cloudinary for image storage. It enables users to browse restaurants, customize orders, track deliveries in real-time, and includes a complete admin panel with CRUD functionality.`,
        subtitle: "How does this app work?",
        description_2: [
            "Browse restaurants and menus with search and category filters",
            "Customize orders and add items to cart with real-time updates",
            "Secure user authentication and registration",
            "View detailed order summary and checkout process",
            "Secure payment processing via Stripe",
            "Real-time order tracking after purchase",
            "Order history for users",
            "Admin panel with full CRUD operations for restaurants, menu items, categories, and orders",
            "Image management with Cloudinary",
            "Fully responsive design (mobile-first)"
        ],
        href: "https://food-4u.netlify.app",
    },
]

export const skills = [
    { name: 'Html/CSS', level: 100 },
    { name: 'React/Redux', level: 100 },
    { name: 'MySQL', level: 100 },
    { name: 'jQuery', level: 100 },
    { name: 'JavaScript', level: 100 },
    { name: 'React Native', level: 100 },
    { name: 'Mongoose', level: 100 },
    { name: 'Angular', level: 55 },
    { name: 'NodeJS', level: 100 },
    { name: 'MongoDB', level: 100 },
    { name: 'Bootstrap', level: 100 },
    { name: 'Vue', level: 95 },
];